import {env} from 'cloudflare:workers';
type B={action?:string;[key:string]:unknown};
const db=()=>{if(!env.DB)throw Error('Database unavailable');return env.DB};
const s=(v:unknown,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:NaN;
const bad=(error:string,status=400)=>Response.json({error},{status});
const fail=(e:unknown)=>{console.error('Cafe API failure',e);const m=e instanceof Error?e.message:'';return bad(m.includes('UNIQUE constraint')?'A duplicate record or active station session exists.':'Request failed. Please retry.',m.includes('UNIQUE constraint')?409:500)};
const methods=['Cash','GCash','Card'];
export async function GET(){try{const d=db();const [stations,customers,plans,sessions,products,sales]=await d.batch([
d.prepare("SELECT s.*,CASE WHEN EXISTS(SELECT 1 FROM sessions x WHERE x.station_id=s.id AND x.status='Active') THEN 1 ELSE 0 END AS occupied FROM stations s ORDER BY s.code"),
d.prepare('SELECT * FROM customers ORDER BY id DESC LIMIT 500'),d.prepare('SELECT * FROM plans ORDER BY id'),
d.prepare('SELECT x.*,s.code AS station_code,s.zone,c.phone AS customer_phone,p.name AS plan_name FROM sessions x JOIN stations s ON s.id=x.station_id LEFT JOIN customers c ON c.id=x.customer_id JOIN plans p ON p.id=x.plan_id ORDER BY x.id DESC LIMIT 500'),
d.prepare('SELECT * FROM products ORDER BY id'),d.prepare('SELECT * FROM sales ORDER BY id DESC LIMIT 200')]);return Response.json({stations:stations.results,customers:customers.results,plans:plans.results,sessions:sessions.results,products:products.results,sales:sales.results})}catch(e){return fail(e)}}
export async function POST(request:Request){let b:B;try{b=await request.json() as B}catch{return bad('Invalid request.')}
try{const d=db(),now=new Date().toISOString();
if(b.action==='seed'){const exists=await d.prepare('SELECT COUNT(*) AS count FROM stations').first<{count:number}>();if(exists?.count)return bad('Sample stations already exist.',409);const inserts=[];for(let i=1;i<=12;i++)inserts.push(d.prepare("INSERT INTO stations(code,zone,specs,status) VALUES(?,?,?,'Available')").bind('PC-'+String(i).padStart(2,'0'),i<=8?'Gaming':'Work & Study',i<=8?'RTX graphics · 144 Hz':'Office suite · headset'));inserts.push(...[['Standard PC',6000,'Everyday browsing and work'],['Gaming PC',9000,'High performance gaming station'],['Premium Gaming',12000,'Competitive setup with peripherals']].map(x=>d.prepare('INSERT INTO plans(name,hourly_cents,description,active) VALUES(?,?,?,1)').bind(...x)));inserts.push(...[['Bottled Water','Drinks',2500,60],['Iced Coffee','Drinks',8500,40],['Instant Noodles','Food',5500,35],['Potato Chips','Snacks',4500,50],['Printing (B&W)','Services',1000,200]].map(x=>d.prepare('INSERT INTO products(name,category,price_cents,stock,active) VALUES(?,?,?,?,1)').bind(...x)));await d.batch(inserts);return Response.json({message:'12 stations, 3 plans and 5 products loaded.'})}
if(b.action==='station'){const code=s(b.code,20).toUpperCase(),zone=s(b.zone,50),specs=s(b.specs,150);if(!code||!zone||!specs)return bad('Enter station code, zone and specs.');await d.prepare("INSERT INTO stations(code,zone,specs,status) VALUES(?,?,?,'Available')").bind(code,zone,specs).run();return Response.json({message:'Station added.'},{status:201})}
if(b.action==='stationStatus'){const id=n(b.id),status=s(b.status,20);if(!Number.isInteger(id)||!['Available','Maintenance'].includes(status))return bad('Invalid station status.');const r=await d.prepare("UPDATE stations SET status=? WHERE id=? AND NOT EXISTS(SELECT 1 FROM sessions WHERE station_id=? AND status='Active')").bind(status,id,id).run();return r.meta.changes?Response.json({message:'Station status updated.'}):bad('Station is occupied or unavailable.',409)}
if(b.action==='customer'){const name=s(b.name,100),phone=s(b.phone,30),email=s(b.email,100);if(!name||phone.length<7||email&&!/^\S+@\S+\.\S+$/.test(email))return bad('Enter a name, phone and optional valid email.');await d.prepare('INSERT INTO customers(name,phone,email,created_at) VALUES(?,?,?,?)').bind(name,phone,email,now).run();return Response.json({message:'Customer added.'},{status:201})}
if(b.action==='plan'){const name=s(b.name,80),description=s(b.description,200),rate=n(b.hourlyCents);if(!name||!description||!Number.isInteger(rate)||rate<100||rate>1e7)return bad('Enter valid rate plan details.');await d.prepare('INSERT INTO plans(name,hourly_cents,description,active) VALUES(?,?,?,1)').bind(name,rate,description).run();return Response.json({message:'Rate plan added.'},{status:201})}
if(b.action==='planStatus'){const id=n(b.id),active=n(b.active);if(!Number.isInteger(id)||![0,1].includes(active))return bad('Invalid plan status.');const r=await d.prepare('UPDATE plans SET active=? WHERE id=?').bind(active,id).run();return r.meta.changes?Response.json({message:'Rate plan updated.'}):bad('Plan not found.',404)}
if(b.action==='start'){const stationId=n(b.stationId),planId=n(b.planId),customerId=b.customerId===null||b.customerId===undefined?null:n(b.customerId),walkIn=s(b.walkIn,100);if(!Number.isInteger(stationId)||!Number.isInteger(planId)||customerId!==null&&!Number.isInteger(customerId)||customerId===null&&!walkIn)return bad('Choose station, plan and registered customer or walk-in name.');const [st,pl,cu]=await d.batch([d.prepare("SELECT id FROM stations WHERE id=? AND status='Available'").bind(stationId),d.prepare('SELECT hourly_cents FROM plans WHERE id=? AND active=1').bind(planId),customerId!==null?d.prepare('SELECT name FROM customers WHERE id=?').bind(customerId):d.prepare("SELECT 'Walk-in' AS name")]);const plan=pl.results[0] as {hourly_cents:number}|undefined,customer=cu.results[0] as {name:string}|undefined;if(!st.results.length||!plan||!customer)return bad('Station, plan or customer unavailable.');const ref='BH-'+crypto.randomUUID().slice(0,8).toUpperCase();const r=await d.prepare("INSERT INTO sessions(reference,station_id,customer_id,customer_name,plan_id,rate_cents,status,started_at) SELECT ?,?,?,?,?,?,'Active',? WHERE NOT EXISTS(SELECT 1 FROM sessions WHERE station_id=? AND status='Active')").bind(ref,stationId,customerId,customerId===null?walkIn:customer.name,planId,plan.hourly_cents,now,stationId).run();return r.meta.changes?Response.json({message:`Session ${ref} started.`,reference:ref},{status:201}):bad('Station already occupied.',409)}
if(b.action==='end'){const id=n(b.id),method=s(b.method,20);if(!Number.isInteger(id)||!methods.includes(method))return bad('Select session and payment method.');const active=await d.prepare("SELECT started_at,rate_cents FROM sessions WHERE id=? AND status='Active'").bind(id).first<{started_at:string;rate_cents:number}>();if(!active)return bad('Session already ended or not found.',409);const minutes=Math.max(15,Math.ceil((Date.now()-Date.parse(active.started_at))/60000)),amount=Math.ceil(minutes*active.rate_cents/60);const r=await d.prepare("UPDATE sessions SET status='Completed',ended_at=?,minutes=?,amount_cents=?,payment_method=? WHERE id=? AND status='Active'").bind(now,minutes,amount,method,id).run();return r.meta.changes?Response.json({message:`Session ended. ${minutes} minutes · ₱${(amount/100).toFixed(2)} collected.`,minutes,amountCents:amount}):bad('Session was just ended.',409)}
if(b.action==='product'){const name=s(b.name,100),category=s(b.category,40),price=n(b.priceCents),stock=n(b.stock);if(!name||!category||!Number.isInteger(price)||price<100||price>1e7||!Number.isInteger(stock)||stock<0||stock>1e6)return bad('Enter valid product details.');await d.prepare('INSERT INTO products(name,category,price_cents,stock,active) VALUES(?,?,?,?,1)').bind(name,category,price,stock).run();return Response.json({message:'Product added.'},{status:201})}
if(b.action==='stock'){const id=n(b.id),delta=n(b.delta);if(!Number.isInteger(id)||!Number.isInteger(delta)||!delta||Math.abs(delta)>1e6)return bad('Enter a valid stock adjustment.');const r=await d.prepare('UPDATE products SET stock=stock+? WHERE id=? AND stock+?>=0').bind(delta,id,delta).run();return r.meta.changes?Response.json({message:'Stock adjusted.'}):bad('Insufficient stock or product unavailable.',409)}
if(b.action==='productStatus'){const id=n(b.id),active=n(b.active);if(!Number.isInteger(id)||![0,1].includes(active))return bad('Invalid product status.');const r=await d.prepare('UPDATE products SET active=? WHERE id=?').bind(active,id).run();return r.meta.changes?Response.json({message:'Product updated.'}):bad('Product not found.',404)}
if(b.action==='sale'){const id=n(b.productId),qty=n(b.quantity),method=s(b.method,20);if(!Number.isInteger(id)||!Number.isInteger(qty)||qty<1||qty>1000||!methods.includes(method))return bad('Enter a valid sale.');const p=await d.prepare('SELECT name,price_cents FROM products WHERE id=? AND active=1').bind(id).first<{name:string;price_cents:number}>();if(!p)return bad('Product unavailable.',404);const decrement=await d.prepare('UPDATE products SET stock=stock-? WHERE id=? AND active=1 AND stock>=?').bind(qty,id,qty).run();if(!decrement.meta.changes)return bad('Not enough stock.',409);const ref='SALE-'+crypto.randomUUID().slice(0,8).toUpperCase();await d.prepare('INSERT INTO sales(reference,product_id,product_name,quantity,unit_cents,total_cents,payment_method,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(ref,id,p.name,qty,p.price_cents,p.price_cents*qty,method,now).run();return Response.json({message:`Sale ${ref} recorded.`,reference:ref},{status:201})}
return bad('Unknown action.')
}catch(e){return fail(e)}}
