"use client";
import {useCallback,useEffect,useState} from 'react';
import {LayoutDashboard,Monitor,Timer,Users,ShoppingBag,SlidersHorizontal,Plus,Search,ArrowRight,ArrowUpRight,ChevronRight,RefreshCw,Menu as MenuIcon,X,Clock3,Gamepad2,Wifi,CheckCircle2,AlertCircle,Coffee,Wallet,Power,Activity,Package,Download} from 'lucide-react';
type Station={id:number;code:string;zone:string;specs:string;status:string;occupied:number};
type Customer={id:number;name:string;phone:string;email:string;created_at:string};
type Plan={id:number;name:string;hourly_cents:number;description:string;active:number};
type Session={id:number;reference:string;station_id:number;station_code:string;zone:string;customer_id:number|null;customer_name:string;customer_phone:string|null;plan_id:number;plan_name:string;rate_cents:number;status:string;started_at:string;ended_at:string|null;minutes:number;amount_cents:number;payment_method:string};
type Product={id:number;name:string;category:string;price_cents:number;stock:number;active:number};
type Sale={id:number;reference:string;product_id:number;product_name:string;quantity:number;unit_cents:number;total_cents:number;payment_method:string;created_at:string};
type Data={stations:Station[];customers:Customer[];plans:Plan[];sessions:Session[];products:Product[];sales:Sale[]};
const empty:Data={stations:[],customers:[],plans:[],sessions:[],products:[],sales:[]};
const php=(c:number)=>'₱'+(c/100).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
const time=(v:string)=>new Date(v).toLocaleString('en-PH',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const elapsed=(v:string,now:number)=>Math.max(0,Math.floor((now-Date.parse(v))/60000));
const duration=(m:number)=>`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`;
const methods=['Cash','GCash','Card'];
export default function Home(){
 const [tab,T]=useState('Overview'),[data,D]=useState<Data>(empty),[modal,M]=useState(''),[form,F]=useState<Record<string,string>>({}),[selected,S]=useState<Session|null>(null),[search,Q]=useState(''),[now,W]=useState(Date.now()),[busy,B]=useState(false),[error,E]=useState(''),[toast,A]=useState(''),[mobile,N]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/cafe');const j=await r.json() as Data&{error?:string};if(!r.ok)throw Error(j.error);D(j)}catch(e){E(e instanceof Error?e.message:'Could not load cafe data.')}},[]);
 useEffect(()=>{void load();const i=setInterval(()=>W(Date.now()),15000);return()=>clearInterval(i)},[load]);useEffect(()=>{if(toast){const i=setTimeout(()=>A(''),4000);return()=>clearTimeout(i)}},[toast]);
 const post=async(body:Record<string,unknown>)=>{B(true);E('');try{const r=await fetch('/api/cafe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(j.error||'Request failed.');A(j.message||'Saved.');M('');F({});await load();return true}catch(e){E(e instanceof Error?e.message:'Request failed.');return false}finally{B(false)}};
 const open=(m:string,session?:Session,station?:Station)=>{E('');F(station?{stationId:String(station.id)}:{});S(session||null);M(m)};
 const active=data.sessions.filter(x=>x.status==='Active'),occupied=data.stations.filter(x=>x.occupied).length,sessionRevenue=data.sessions.filter(x=>x.status==='Completed').reduce((a,x)=>a+x.amount_cents,0),salesRevenue=data.sales.reduce((a,x)=>a+x.total_cents,0);
 const selectedCurrent=data.sessions.find(x=>x.id===selected?.id)||selected;
 const estimate=selectedCurrent?Math.ceil(Math.max(15,Math.ceil((now-Date.parse(selectedCurrent.started_at))/60000))*selectedCurrent.rate_cents/60):0;
 const submit=async()=>{if(modal==='station')await post({action:'station',...form});if(modal==='customer')await post({action:'customer',...form});if(modal==='plan')await post({action:'plan',name:form.name,description:form.description,hourlyCents:Math.round(Number(form.rate)*100)});if(modal==='start')await post({action:'start',stationId:Number(form.stationId),planId:Number(form.planId),customerId:form.customerId?Number(form.customerId):null,walkIn:form.walkIn});if(modal==='end'&&selectedCurrent)await post({action:'end',id:selectedCurrent.id,method:form.method||'Cash'});if(modal==='product')await post({action:'product',name:form.name,category:form.category,priceCents:Math.round(Number(form.price)*100),stock:Number(form.stock)});if(modal==='stock')await post({action:'stock',id:Number(form.productId),delta:Number(form.delta)});if(modal==='sale')await post({action:'sale',productId:Number(form.productId),quantity:Number(form.quantity),method:form.method||'Cash'})};
 const exportCSV=()=>{const rows=[['Reference','Station','Customer','Plan','Start','End','Minutes','Total PHP','Payment'],...data.sessions.map(s=>[s.reference,s.station_code,s.customer_name,s.plan_name,s.started_at,s.ended_at||'',String(s.minutes),(s.amount_cents/100).toFixed(2),s.payment_method])].map(row=>row.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\r\n')],{type:'text/csv'}));a.download='bytehaven-sessions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const nav=[{name:'Overview',icon:LayoutDashboard},{name:'Stations',icon:Monitor},{name:'Sessions',icon:Timer},{name:'Customers',icon:Users},{name:'Shop & Sales',icon:ShoppingBag},{name:'Rates & Settings',icon:SlidersHorizontal}];
 const go=(name:string)=>{T(name);N(false);E('')};
 return <div className="app"><aside className={'sidebar '+(mobile?'open':'')}><button className="brand" onClick={()=>go('Overview')}><span className="brand-mark"><Gamepad2 size={23}/></span><span>BYTE<span className="accent">HAVEN</span><small>INTERNET CAFÉ MANAGER</small></span></button><div className="nav-label">WORKSPACE</div><nav>{nav.map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>go(name)}><Icon size={18}/>{name}{tab===name&&<ChevronRight className="nav-chevron" size={16}/>}</button>)}</nav><div className="sidebar-foot"><div className="side-promo"><span><Activity size={19}/></span><strong>Stay in control</strong><p>Live stations, clear sessions, and every sale in one place.</p></div><div className="operator"><span>BH</span><div><strong>Front desk</strong><small>Operator workspace</small></div></div></div></aside>
 <main className="main"><header className="topbar"><button className="menu-toggle" onClick={()=>N(!mobile)} aria-label="Toggle navigation">{mobile?<X/>:<MenuIcon/>}</button><div className="breadcrumb">Workspace <ChevronRight size={14}/> <strong>{tab}</strong></div><div className="topbar-right"><span className="live"><span/> LIVE OPERATIONS</span><span className="today">{new Date(now).toLocaleDateString('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</span><button title="Refresh" onClick={()=>void load()}><RefreshCw size={18}/></button><span className="user-dot">BH</span></div></header><div className="content"><div className="page-title"><div><span className="eyebrow">CONTROL CENTER / {tab.toUpperCase()}</span><h1>{tab==='Overview'?'Everything, in real time.':tab}</h1><p>{tab==='Overview'?'Your café floor, sessions, and earnings at a glance.':tab==='Stations'?'Every station, every status, all in one view.':tab==='Sessions'?'Monitor active timers and completed visits.':tab==='Customers'?'Keep your regulars close.':tab==='Shop & Sales'?'Snacks, drinks, printing, and quick sales.':'Set the prices and stations that keep you running.'}</p></div><div className="heading-actions">{tab==='Stations'&&<button className="primary" onClick={()=>open('station')}><Plus size={17}/> Add station</button>}{tab==='Sessions'&&<><button className="secondary" onClick={exportCSV}><Download size={16}/> Export CSV</button><button className="primary" onClick={()=>open('start')}><Plus size={17}/> Start session</button></>}{tab==='Customers'&&<button className="primary" onClick={()=>open('customer')}><Plus size={17}/> Add customer</button>}{tab==='Shop & Sales'&&<><button className="secondary" onClick={()=>open('stock')}><Package size={17}/> Adjust stock</button><button className="primary" onClick={()=>open('sale')}><Plus size={17}/> New sale</button></>}{tab==='Rates & Settings'&&<button className="primary" onClick={()=>open('plan')}><Plus size={17}/> Add rate plan</button>}</div></div>
 {error&&!modal&&<div className="error-banner"><AlertCircle size={16}/>{error}<button onClick={()=>E('')}>Dismiss</button></div>}
 {tab==='Overview'&&<><section className="hero"><div><span className="hero-kicker"><span className="live-point"/> YOUR CAFÉ IS ONLINE</span><h2>Make every minute count.</h2><p>One clean view of your stations, your people, and the work happening right now.</p><button onClick={()=>open('start')}>Start a session <ArrowUpRight size={17}/></button></div><div className="hero-graphic" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="hero-screen"><Monitor size={70} strokeWidth={1.2}/><span>BH<span className="accent">_</span></span></div><span className="graphic-dot d1"/><span className="graphic-dot d2"/><span className="graphic-dot d3"/></div></section><div className="stats"><Metric icon={<Monitor size={21}/>} label="Stations in use" value={`${occupied} / ${data.stations.length}`} hint={`${data.stations.filter(s=>s.status==='Available'&&!s.occupied).length} ready to use`} color="purple"/><Metric icon={<Timer size={21}/>} label="Active sessions" value={String(active.length)} hint="Timers running right now" color="mint"/><Metric icon={<Wallet size={21}/>} label="Session revenue" value={php(sessionRevenue)} hint="From completed sessions" color="orange"/><Metric icon={<ShoppingBag size={21}/>} label="Shop sales" value={php(salesRevenue)} hint={`${data.sales.length} recorded sales`} color="blue"/></div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">LIVE FLOOR</span><h3>Active sessions</h3></div><button onClick={()=>go('Sessions')}>View all <ArrowUpRight size={15}/></button></div>{active.length?<div className="live-list">{active.slice(0,6).map(x=><div key={x.id} className="live-row"><span className="station-ico"><Monitor size={19}/></span><div><strong>{x.station_code} <small>· {x.customer_name}</small></strong><span>{x.plan_name} · Started {time(x.started_at)}</span></div><div className="live-duration"><strong>{duration(elapsed(x.started_at,now))}</strong><button onClick={()=>open('end',x)}>End <ArrowRight size={13}/></button></div></div>)}</div>:<Empty text="No sessions running. Start one to see it here."/>}</section><section className="panel quick-panel"><div className="panel-head"><div><span className="eyebrow">AT A GLANCE</span><h3>Station availability</h3></div><Wifi size={18}/></div><div className="quick-stations">{data.stations.slice(0,12).map(st=><button key={st.id} className={st.occupied?'occupied':st.status==='Maintenance'?'maintenance':'ready'} onClick={()=>{go('Stations')}}><Monitor size={17}/><strong>{st.code}</strong><span>{st.occupied?'In use':st.status==='Maintenance'?'Offline':'Ready'}</span></button>)}</div><div className="quick-foot"><CheckCircle2 size={17}/>{data.stations.filter(s=>s.status==='Available'&&!s.occupied).length} stations available for the next guest</div></section></div></>}
 {tab==='Stations'&&<><div className="station-legend"><span><i className="ready"/>Available</span><span><i className="occupied"/>In use</span><span><i className="maintenance"/>Maintenance</span></div><div className="station-grid">{data.stations.map(st=>{const running=active.find(x=>x.station_id===st.id);return <div className={'station-card '+(running?'in-use':st.status==='Maintenance'?'offline':'')} key={st.id}><div className="station-top"><span className="station-icon"><Monitor size={24}/></span><span className={'state '+(running?'busy':st.status==='Maintenance'?'offline':'ready')}><i/>{running?'In use':st.status==='Maintenance'?'Maintenance':'Available'}</span></div><span className="station-zone">{st.zone.toUpperCase()}</span><h3>{st.code}</h3><p>{st.specs}</p>{running?<div className="station-active"><div><small>ACTIVE GUEST</small><strong>{running.customer_name}</strong></div><div><small>ELAPSED</small><strong>{duration(elapsed(running.started_at,now))}</strong></div></div>:<div className="station-active quiet">{st.status==='Maintenance'?'Unavailable for sessions':'Ready for the next session'}</div>}<div className="station-actions">{running?<button className="primary" onClick={()=>open('end',running)}>End session <ArrowRight size={15}/></button>:st.status==='Available'?<button className="primary" onClick={()=>open('start',undefined,st)}>Start session <ArrowRight size={15}/></button>:<button className="secondary" disabled={busy} onClick={()=>void post({action:'stationStatus',id:st.id,status:'Available'})}>Mark available</button>}{!running&&st.status==='Available'&&<button className="link-button" disabled={busy} onClick={()=>void post({action:'stationStatus',id:st.id,status:'Maintenance'})}>Set maintenance</button>}</div></div>})}</div>{!data.stations.length&&<Empty text="No stations yet. Add one or load the sample setup."/>}</>}
 {tab==='Sessions'&&<><div className="tabs-stats"><div><span className="pulse"/> {active.length} active right now</div><div>{data.sessions.filter(x=>x.status==='Completed').length} completed</div></div><section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">SESSION HISTORY</span><h3>All sessions</h3></div><div className="search"><Search size={16}/><input placeholder="Search customer, station or reference" value={search} onChange={e=>Q(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>SESSION</th><th>CUSTOMER</th><th>STATION / PLAN</th><th>TIME</th><th>STATUS</th><th>AMOUNT</th><th></th></tr></thead><tbody>{data.sessions.filter(x=>`${x.reference} ${x.customer_name} ${x.station_code}`.toLowerCase().includes(search.toLowerCase())).map(x=><tr key={x.id}><td><strong className="ref">{x.reference}</strong><small>{time(x.started_at)}</small></td><td><strong>{x.customer_name}</strong><small>{x.customer_phone||'Walk-in'}</small></td><td><strong>{x.station_code}</strong><small>{x.plan_name}</small></td><td><strong>{x.status==='Active'?duration(elapsed(x.started_at,now)):duration(x.minutes)}</strong><small>{x.status==='Active'?'Running':x.ended_at?time(x.ended_at):''}</small></td><td><span className={'state '+(x.status==='Active'?'busy':'ready')}><i/>{x.status}</span></td><td><strong>{x.status==='Active'?php(Math.ceil(Math.max(15,Math.ceil((now-Date.parse(x.started_at))/60000))*x.rate_cents/60)):php(x.amount_cents)}</strong><small>{x.status==='Active'?'Est.':x.payment_method}</small></td><td>{x.status==='Active'&&<button className="small-action" onClick={()=>open('end',x)}>End <ArrowRight size={14}/></button>}</td></tr>)}</tbody></table></div>{!data.sessions.length&&<Empty text="Sessions will show up here once you start a timer."/>}</section></>}
 {tab==='Customers'&&<section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">REGULARS & WALK-INS</span><h3>Customer directory</h3></div><span className="count">{data.customers.length} customers</span></div><div className="table-wrap"><table><thead><tr><th>CUSTOMER</th><th>PHONE</th><th>EMAIL</th><th>SESSIONS</th><th>JOINED</th></tr></thead><tbody>{data.customers.map(c=><tr key={c.id}><td><span className="customer-cell"><span>{c.name.slice(0,2).toUpperCase()}</span><strong>{c.name}</strong></span></td><td>{c.phone}</td><td>{c.email||'—'}</td><td><span className="number-pill">{data.sessions.filter(x=>x.customer_id===c.id).length}</span></td><td>{new Date(c.created_at).toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'})}</td></tr>)}</tbody></table></div>{!data.customers.length&&<Empty text="Add a customer to keep track of visits."/>}</section>}
 {tab==='Shop & Sales'&&<><div className="shop-top"><div><span className="eyebrow">QUICK COUNTER</span><h3>Products & services</h3><p>Sell snacks, drinks, and counter services in a few clicks.</p></div><button className="secondary" onClick={()=>open('product')}><Plus size={16}/> Add product</button></div><div className="product-grid">{data.products.map(p=><div className="product-card" key={p.id}><span className={'product-icon '+p.category.toLowerCase()}>{p.category==='Drinks'?<Coffee size={22}/>:p.category==='Services'?<Package size={22}/>:<ShoppingBag size={22}/>}</span><span className="product-category">{p.category.toUpperCase()}</span><h3>{p.name}</h3><div className="product-bottom"><strong>{php(p.price_cents)}</strong><span>{p.stock} in stock</span></div><button className="product-toggle" disabled={busy} onClick={()=>void post({action:'productStatus',id:p.id,active:p.active?0:1})}>{p.active?'Available · click to disable':'Unavailable · click to enable'}</button></div>)}</div><section className="panel table-panel" style={{marginTop:24}}><div className="panel-head"><div><span className="eyebrow">POINT OF SALE</span><h3>Recent sales</h3></div><span className="count">{php(salesRevenue)} total</span></div><div className="table-wrap"><table><thead><tr><th>SALE</th><th>PRODUCT</th><th>QUANTITY</th><th>METHOD</th><th>TIME</th><th>TOTAL</th></tr></thead><tbody>{data.sales.map(x=><tr key={x.id}><td><strong className="ref">{x.reference}</strong></td><td>{x.product_name}</td><td>{x.quantity}</td><td>{x.payment_method}</td><td>{time(x.created_at)}</td><td><strong>{php(x.total_cents)}</strong></td></tr>)}</tbody></table></div>{!data.sales.length&&<Empty text="Counter sales will appear here."/>}</section></>}
 {tab==='Rates & Settings'&&<><div className="shop-top"><div><span className="eyebrow">PRICING</span><h3>Session rate plans</h3><p>Rates are captured when a session begins, so changing a plan will not change an active timer.</p></div></div><div className="plan-grid">{data.plans.map(p=><div className="plan-card" key={p.id}><span className="plan-icon"><Gamepad2 size={25}/></span><span className="plan-status">{p.active?'ACTIVE':'INACTIVE'}</span><h3>{p.name}</h3><p>{p.description}</p><div className="plan-price"><strong>{php(p.hourly_cents)}</strong><small>/ hour</small></div><button disabled={busy} onClick={()=>void post({action:'planStatus',id:p.id,active:p.active?0:1})}>{p.active?'Deactivate':'Activate'}</button></div>)}</div>{!data.plans.length&&<Empty text="Create a rate plan or load the sample setup to get started."/>}</>}
 {!data.stations.length&&tab==='Overview'&&<div className="setup"><div><span className="eyebrow">FIRST THINGS FIRST</span><h3>Set up your café in one click.</h3><p>Load 12 demo stations, 3 hourly rate plans, and 5 counter products.</p></div><button className="primary" disabled={busy} onClick={()=>void post({action:'seed'})}>Load sample setup <ArrowRight size={16}/></button></div>}
 <footer>© 2026 ByteHaven · Powering every great session.</footer></div></main>
 {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}<button onClick={()=>A('')}>×</button></div>}
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)M('')}}><div className="dialog"><div className="dialog-head"><div><span className="eyebrow">BYTEHAVEN OPERATIONS</span><h2>{{station:'Add station',customer:'Add customer',plan:'Add rate plan',start:'Start session',end:'End session & collect',product:'Add product',stock:'Adjust stock',sale:'New sale'}[modal]||modal}</h2></div><button onClick={()=>M('')} aria-label="Close"><X size={20}/></button></div>{error&&<div className="form-error"><AlertCircle size={16}/>{error}</div>}
 {modal==='station'&&<div className="fields"><Field label="Station code *" value={form.code} change={v=>F({...form,code:v})} placeholder="PC-13"/><Field label="Zone *" value={form.zone} change={v=>F({...form,zone:v})} placeholder="Gaming"/><Field label="Specifications *" value={form.specs} change={v=>F({...form,specs:v})} placeholder="RTX graphics · 144 Hz"/></div>}
 {modal==='customer'&&<div className="fields"><Field label="Name *" value={form.name} change={v=>F({...form,name:v})} placeholder="Juan Dela Cruz"/><Field label="Phone *" value={form.phone} change={v=>F({...form,phone:v})} placeholder="0917 123 4567"/><Field label="Email" value={form.email} change={v=>F({...form,email:v})} placeholder="Optional"/></div>}
 {modal==='plan'&&<div className="fields"><Field label="Plan name *" value={form.name} change={v=>F({...form,name:v})} placeholder="Premium Gaming"/><Field label="Hourly rate (₱) *" type="number" value={form.rate} change={v=>F({...form,rate:v})} placeholder="120"/><Field label="Description *" value={form.description} change={v=>F({...form,description:v})} placeholder="High-performance gaming setup"/></div>}
 {modal==='start'&&<div className="fields"><label>Station *<select value={form.stationId||''} onChange={e=>F({...form,stationId:e.target.value})}><option value="">Choose available station</option>{data.stations.filter(st=>st.status==='Available'&&!st.occupied).map(st=><option key={st.id} value={st.id}>{st.code} · {st.zone}</option>)}</select></label><label>Rate plan *<select value={form.planId||''} onChange={e=>F({...form,planId:e.target.value})}><option value="">Choose rate plan</option>{data.plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · {php(p.hourly_cents)}/hr</option>)}</select></label><label>Registered customer<select value={form.customerId||''} onChange={e=>F({...form,customerId:e.target.value})}><option value="">Walk-in guest</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label>{!form.customerId&&<Field label="Walk-in name *" value={form.walkIn} change={v=>F({...form,walkIn:v})} placeholder="Guest name"/>}<div className="field-note">Billing starts now and is rounded up to the minute, with a 15-minute minimum.</div></div>}
 {modal==='end'&&selectedCurrent&&<><div className="session-summary"><span className="eyebrow">{selectedCurrent.reference}</span><h3>{selectedCurrent.station_code} · {selectedCurrent.customer_name}</h3><div><span>Elapsed</span><strong>{duration(elapsed(selectedCurrent.started_at,now))}</strong></div><div><span>Plan</span><strong>{selectedCurrent.plan_name} · {php(selectedCurrent.rate_cents)}/hr</strong></div><div className="total"><span>Estimated charge</span><strong>{php(estimate)}</strong></div><small>Final amount is recalculated at the time you end the session.</small></div><div className="fields"><label>Payment method<select value={form.method||'Cash'} onChange={e=>F({...form,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label></div></>}
 {modal==='product'&&<div className="fields"><Field label="Name *" value={form.name} change={v=>F({...form,name:v})} placeholder="Iced Coffee"/><Field label="Category *" value={form.category} change={v=>F({...form,category:v})} placeholder="Drinks"/><Field label="Price (₱) *" type="number" value={form.price} change={v=>F({...form,price:v})} placeholder="85"/><Field label="Starting stock *" type="number" value={form.stock} change={v=>F({...form,stock:v})} placeholder="40"/></div>}
 {modal==='stock'&&<div className="fields"><label>Product *<select value={form.productId||''} onChange={e=>F({...form,productId:e.target.value})}><option value="">Choose product</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.stock} left</option>)}</select></label><Field label="Change in stock *" type="number" value={form.delta} change={v=>F({...form,delta:v})} placeholder="10 to add, -5 to remove"/></div>}
 {modal==='sale'&&<div className="fields"><label>Product *<select value={form.productId||''} onChange={e=>F({...form,productId:e.target.value})}><option value="">Choose available product</option>{data.products.filter(p=>p.active&&p.stock>0).map(p=><option key={p.id} value={p.id}>{p.name} · {php(p.price_cents)} · {p.stock} left</option>)}</select></label><Field label="Quantity *" type="number" value={form.quantity} change={v=>F({...form,quantity:v})} placeholder="1"/><label>Payment method<select value={form.method||'Cash'} onChange={e=>F({...form,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label>{form.productId&&form.quantity&&<div className="field-note total-preview">Total <strong>{php((data.products.find(p=>p.id===Number(form.productId))?.price_cents||0)*Number(form.quantity))}</strong></div>}</div>}
 <div className="dialog-actions"><button className="secondary" onClick={()=>M('')}>Cancel</button><button className="primary" disabled={busy} onClick={()=>void submit()}>{busy?'Saving...':modal==='end'?'End & collect':modal==='start'?'Start timer':modal==='sale'?'Record sale':'Save'} <ArrowRight size={16}/></button></div></div></div>}
 </div>}
function Metric({icon,label,value,hint,color}:{icon:React.ReactNode;label:string;value:string;hint:string;color:string}){return <div className="metric"><span className={'metric-icon '+color}>{icon}</span><small>{label}</small><strong>{value}</strong><span>{hint}</span></div>}
function Field({label,value,change,placeholder,type='text'}:{label:string;value?:string;change:(v:string)=>void;placeholder?:string;type?:string}){return <label>{label}<input type={type} step={type==='number'?'any':undefined} value={value||''} onChange={e=>change(e.target.value)} placeholder={placeholder}/></label>}
function Empty({text}:{text:string}){return <div className="empty"><Monitor size={28}/><p>{text}</p></div>}
